export const CATEGORIES = [
  '👗 Clothes & Fashion',
  '💍 Imitation Jewelry',
  '🍪 Homemade Snacks & Sweets',
  '🍱 Tiffin / Dabba Services',
  '🧴 Beauty & Skincare Products',
  '🪔 Handicrafts & Decorative Items',
  '🎁 Gift & Handmade Items',
  '🖊️ Stationery / Printed Items',
  '🧵 Stitching / Tailoring',
  '🍼 Baby Care Products',
  '💼 Jobs',
];


export const LOCATIONS = [
  'Sukhnath Para',
  'Near Pathak School Amreli',
  'Sankul',
  'GIDC Area (Amreli)',
  'Pragati Nagar',
  'Hanumanpara',
  'Jesingpara',
  'Mani Nagar',
  'Yogi Nagar',
  'Panihari Society',
  'D.L.B. Society',
  'Ranuja Dham Society',
  'Bhojal Para',
  'Bhav Nagar',
  'Royal Park',
  'Near Post Office Area',
  'Gangapark Society, Keriya Road, Mahila Mandir Amreli',
  'Lathi Road Area',
  'Jilla Panchayat Road',
  'Library Road',
  'Bhavnagar Road (Near Railway Crossing)',
  'Liliya Road'
];

export const SOCIAL_LINKS = {
  facebook: 'https://www.facebook.com/rushikeshpatel05',
  instagram: 'https://www.instagram.com/rushikeshpatel05/',
  github: 'https://github.com/rrbhanderi05/',
};

export const MOCK_BUSINESSES: Business[] = [
  {
    id: '1',
    name: 'Patel General Store',
    description: 'A one-stop shop for all your daily needs with quality products at affordable prices.',
    category: 'Retail',
    location: 'Amreli City',
    contact: '+91 9876543210',
    whatsapp: '+919876543210',
    imageUrl: 'https://images.pexels.com/photos/264547/pexels-photo-264547.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: '2',
    name: 'Gujarati Thali Restaurant',
    description: 'Authentic Gujarati cuisine serving delicious thalis and snacks in a family-friendly environment.',
    category: 'Restaurant',
    location: 'Amreli City',
    contact: '+91 9876543211',
    whatsapp: '+919876543211',
    imageUrl: 'https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: '3',
    name: 'Mehta Computer Services',
    description: 'Professional computer repair, software installation, and IT support for homes and businesses.',
    category: 'Technology',
    location: 'Savarkundla',
    contact: '+91 9876543212',
    whatsapp: '+919876543212',
    imageUrl: 'https://images.pexels.com/photos/4792731/pexels-photo-4792731.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: '4',
    name: 'Krishna Beauty Parlour',
    description: 'Full-service beauty salon offering haircuts, styling, makeup, and bridal packages at competitive prices.',
    category: 'Beauty',
    location: 'Dhari',
    contact: '+91 9876543213',
    whatsapp: '+919876543213',
    imageUrl: 'https://images.pexels.com/photos/3992874/pexels-photo-3992874.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: '5',
    name: 'Shree Home Services',
    description: 'Professional plumbing, electrical, and carpentry services with experienced and reliable technicians.',
    category: 'Home Services',
    location: 'Lathi',
    contact: '+91 9876543214',
    whatsapp: '+919876543214',
    imageUrl: 'https://images.pexels.com/photos/4108271/pexels-photo-4108271.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: '6',
    name: 'Amreli Tuition Classes',
    description: 'Expert coaching for students from 5th to 12th standard with a focus on math and science subjects.',
    category: 'Education',
    location: 'Amreli City',
    contact: '+91 9876543215',
    whatsapp: '+919876543215',
    imageUrl: 'https://images.pexels.com/photos/301926/pexels-photo-301926.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
];